ssl_verify_client optional;
ssl_client_certificate conf.d/rootca.crt;

geo $remote_addr $is_external {
    default           1;
    127.0.0.1         0;
    ::1               0;
    192.168.178.0/24  0;
}
map $ssl_client_verify $mtls_failed {
    default 1;
    SUCCESS 0;
}
map "$is_external:$mtls_failed" $reject_mtls {
  default 0;
  1:1     1;
}
