version: "3"

services:
  samba:
    image: dperson/samba
    environment:
      USER: ${SAMBA_USER};${SAMBA_PASS}
      USERID: 1000
      GROUPID: 1000
      SHARE1: server_home;/share1;no;no;no;${SAMBA_USER}
      SHARE2: server_ssd;/share2;no;no;no;${SAMBA_USER}
    ports:
      - 139:139
      - 445:455
    volumes:
      - ${FOLDER_1}:/share1
      - ${FOLDER_2}:/share2
