version: "3"

services:
  cloudflared:
    image: cloudflare/cloudflared
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_ADDRESS: 0.0.0.0
    networks:
      internal_network:
        ipv4_address: 172.30.9.2
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    volumes:
      - /home/earlopain/pihole/etc:/etc/pihole
      - /home/earlopain/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    domainname: server.lan
    mac_address: d0:ca:ab:cd:ef:01
    networks:
      internal_network:
        ipv4_address: 172.30.9.3
      pihole_network:
        ipv4_address: 192.168.178.51
    environment:
      TZ: Europe/Berlin
      VIRTUAL_HOST: pihole.server.lan
      WEBPASSWORD: test
      PIHOLE_DNS_: 172.30.9.2#5053
      DNSSEC: true
      DNSMASQ_LISTENING: all
      FTLCONF_DBINTERVAL: 60
      FTLCONF_REPLY_ADDR4: 192.168.178.51
      DHCP_ACTIVE: true
      DHCP_START: 192.168.178.151
      DHCP_END: 192.168.178.251
      DHCP_ROUTER: 192.168.178.1
      DHCP_LEASETIME: 744
    depends_on:
      - cloudflared
    restart: unless-stopped

networks:
  internal_network:
    ipam:
      config:
        - subnet: 172.30.9.0/29
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: 192.168.178.0/24
          gateway: 192.168.178.1
          ip_range: 192.168.178.1/24
