version: "3"

services:
  cloudflared:
    image: cloudflare/cloudflared
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_ADDRESS: 0.0.0.0
    network_mode: host
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    volumes:
      - /home/earlopain/pihole/etc:/etc/pihole
      - ${PWD}/pihole.custom.list:/etc/pihole/custom.list
      - /home/earlopain/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      VIRTUAL_HOST: pihole.server.lan
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      WEB_PORT: 8081
      PIHOLE_DNS_: 127.0.0.1#5053
      DNSSEC: true
      DNSMASQ_LISTENING: all
      FTLCONF_DBINTERVAL: 60
      FTLCONF_REPLY_ADDR4: 192.168.178.50
      DHCP_ACTIVE: true
      DHCP_START: 192.168.178.151
      DHCP_END: 192.168.178.251
      DHCP_ROUTER: 192.168.178.1
      DHCP_LEASETIME: 744
    depends_on:
      - cloudflared
    restart: unless-stopped
