services:
  traccar:
    image: traccar/traccar:6.10.0-alpine
    ports:
      - 8082:8082
    volumes:
      - ${FOLDER_1}/traccar/data:/opt/traccar/data
      - ./traccar.xml:/opt/traccar/conf/traccar.xml
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: true
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_URL: jdbc:postgresql://postgres:5432/traccar
      DATABASE_USER: traccar
      DATABASE_PASSWORD: traccar
    restart: unless-stopped

  postgres:
    image: postgres:18.0-alpine
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: traccar
    volumes:
      - ${FOLDER_1}/traccar/db:/var/lib/postgresql/data
    restart: unless-stopped
