services:
  traccar:
    image: traccar/traccar:6.7-alpine
    ports:
      - 8082:8082
    volumes:
      - ${FOLDER_1}/traccar:/opt/traccar/data
      - ./traccar.xml:/opt/traccar/conf/traccar.xml
    restart: unless-stopped
