services:
  traccar:
    image: traccar/traccar:6.6-alpine
    ports:
      - 8082:8082
    volumes:
      - data:/opt/traccar/data
      - ./traccar.xml:/opt/traccar/conf/traccar.xml
    restart: unless-stopped

volumes:
  data:
