services:
  cloudflared:
    image: cloudflare/cloudflared:2025.2.1-amd64
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_ADDRESS: 0.0.0.0
    network_mode: host
    restart: unless-stopped

  pihole:
    image: pihole/pihole:2025.04.0
    volumes:
      - ${FOLDER_1}/pihole/etc:/etc/pihole
      - ${SERVER_PROJECT_DIR}/pihole/custom.list:/etc/pihole/custom.list
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_webserver_port: 8081
      FTLCONF_dns_upstreams: 127.0.0.1#5053
      FTLCONF_dns_domain: earlopain.dev
      FTLCONF_dns_dnssec: false
      FTLCONF_dns_bogusPriv: true
      FTLCONF_dns_domainNeeded: true
      FTLCONF_dns_listeningMode: local
      FTLCONF_dns_reply_host_IPv4: 192.168.178.50
      FTLCONF_dhcp_active: true
      FTLCONF_dhcp_start: 192.168.178.151
      FTLCONF_dhcp_end: 192.168.178.251
      FTLCONF_dhcp_router: 192.168.178.1
      FTLCONF_dhcp_leaseTime: 744
      FTLCONF_misc_dnsmasq_lines: no-0x20-encode
    depends_on:
      - cloudflared
    restart: unless-stopped
