version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.20.1
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  agent:
    image: portainer/agent:2.20.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped

volumes:
  data:
